[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[build.environment]
  BUN_VERSION = "1.2.3"

[build]
  command = "curl -fsSL https://bun.sh/install | bash && export BUN_INSTALL=$HOME/.bun && export PATH=$PATH:$HOME/.bun/bin && bun run build"
